// example/pagination/basic.vue
<template>
  <pagination :total="24" :current="current" :on-change="updateCurrent" :visible-count="5"></pagination>

  <pagination :total="24" :current="current" :visible-count="9" :on-change="updateCurrent" size="sm"></pagination>
</template>

<script>
import pagination from 'component/pagination'

export default {
  data() {
    return {
      current: 1
    }
  },
  components: {
    pagination
  },
  methods: {
    updateCurrent(page) {
      this.current = page
    }
  }
}
</script>

// example/pagination/basic.jsx
import pagination from 'component/pagination'

export default {
  data() {
    return {
      current: 1
    }
  },
  components: {
    pagination
  },
  methods: {
    updateCurrent(page) {
      this.current = page
    }
  },
  render(h) {
    return (
      <div>
        <pagination total={24}
                    current={this.current}
                    onChange={this.updateCurrent}
                    visibleCount={5}></pagination>

        <pagination total={24}
                    current={this.current}
                    visibleCount={9}
                    onChange={this.updateCurrent}
                    size="sm"></pagination>
      </div>
    )
  }
}
