// example/drop-down-old/drop-down-menu.vue
<template>
  <x-drop-down-menu
          label="drop down menu"
          :items="items"
          item-label="label"
          btn-type="primary"></x-drop-down-menu>
</template>

<script>
  export default {
    data() {
      return {
        items: [
          {
            label: 'item1'
          },
          {
            divider: true
          },
          {
            label: 'disabled item',
            disabled: true
          }
        ]
      }
    },
    methods: {
      handleClick(e, item) {
        console.log(e, item)
      }
    }
  }
</script>

// example/drop-down/drop-down-menu.jsx
export default {
  data() {
    return {
      menu: [{
        label: 'test1'
      }, {
        label: 'test2'
      }, {
        divider: true
      }, {
        label: 'test3'
      }]
    }
  },
  methods: {
    menuItemHandleClick(arg) {
      console.log(arg)
    }
  },
  render(h) {
    return (
        <div style={{ textAlign: 'center' }}>
          <div>
            <h2>x-drop-down-menu</h2>
            <br/><br/><br/>
            <h3>left</h3>
            <x-drop-down-menu
                label="test"
                btnType="danger"
                alignment="left"
                domProps-menuItemHandleClick={ this.menuItemHandleClick }
                domProps-menu={ this.menu }/>
            <h3>right</h3>
            <x-drop-down-menu
                label="test"
                btnType="danger"
                alignment="right"
                domProps-menuItemHandleClick={ this.menuItemHandleClick }
                domProps-menu={ this.menu }/>
            <h3>top</h3>
            <x-drop-down-menu
                label="test"
                btnType="danger"
                alignment="top"
                domProps-menuItemHandleClick={ this.menuItemHandleClick }
                domProps-menu={ this.menu }/>
            <h3>bottom</h3>
            <x-drop-down-menu
                label="test"
                btnType="danger"
                alignment="bottom"
                domProps-menuItemHandleClick={ this.menuItemHandleClick }
                domProps-menu={ this.menu }/>
          </div>
          <br/><br/><br/><br/><br/>
        </div>
    )
  }
}
